first_name_loc = 'firstname'
last_name_loc = 'lastname'
email_loc = 'email_address'
password_loc = 'password'
confirm_password_loc = 'password-confirmation'
create_button_loc = '.submit'
greet_message_loc = '[data-bind="html: $parent.prepareMessageForHtml(message.text)"]'
header_title_loc = '[class="page-title"]'
check_information_loc = '//*[@class="box-content"]/p'
error_different_password_loc = '[id="password-confirmation-error"]'
error_empty_first_name_loc = 'firstname-error'
error_empty_last_name_loc = 'lastname-error'
error_empty_email_loc = 'email_address-error'
error_empty_password_loc = 'password-error'
error_empty_confirm_password_loc = 'password-confirmation-error'
