cards_loc = '.product-image-photo'
name_item_loc = '.product-item-link'
size_loc = '[option-label="29"]'
color_loc = '[option-label="Orange"]'
button_cart_loc = '[title="Add to Cart"]'
message_successful_added_loc = '[data-bind="html: $parent.prepareMessageForHtml(message.text)"]'
# cart_loc = (By.LINK_TEXT, 'shopping cart')
name_in_cart_loc = '(//div[@class="product-item-details"]//strong[@class="product-item-name"]/a)[2]'
cart_icon_loc = '[class = "action showcart"]'
cart_icon_item_name_loc = '[data-bind="attr: {href: product_url}, html: product_name"]'
remove_icon_loc = '[title="Remove item"]'
alert_accept_loc = '.action-accept'
inform_message_loc = '[class="subtitle empty"]'
select_sort_loc = '[data-role="sorter"]'
price_loc = '[data-price-type="finalPrice"]'
